version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    labels:
      me.adoopt.description: "Postgres Database"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432