version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: unless-stopped
    labels:
      me.adoopt.description: "Postgres Database"
    ports:
      - 5434:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - adooptame
networks:
  adooptame: